/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */

repositories {
    mavenCentral()
}

plugins {
    kotlin("jvm") version "1.3.71"
}


apply(plugin = "kotlin")

dependencies {
    implementation(kotlin("stdlib"))
    implementation("io.arrow-kt:arrow-mtl:0.10.4")
}